apiVersion: v1
kind: Secret
metadata:
  name: sts-delegate-rs-secrets
  namespace: sts-delegate-rs
  labels:
    app.kubernetes.io/name: sts-delegate-rs
type: Opaque
stringData:
  obo_sts_private_key.json: "REPLACE_WITH_PRIVATE_STS_SIGNING_JWK"
  actor_jwks.json: "REPLACE_WITH_PUBLIC_ACTOR_JWKS"
  client_jwks.json: "REPLACE_WITH_PUBLIC_CLIENT_JWKS"
  idp_jwks.json: "REPLACE_WITH_PUBLIC_IDP_JWKS"
